services:
  frontend:
    build: ./url-shortener
    ports:
      - "3000:3000"
    # stdin_open: true
    # tty: true
    depends_on:
      - backend
    volumes:
      - ./url-shortener:/app
      # - /app/node_modules

  backend:
    build: ./url-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url_db
      - APP_ORIGIN=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./url-server:/app
      # - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
